[package]
name = "rust-markdown"
version = "0.1.0"
authors = ["Matt White <code@typenil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
